export enum AppRoutePaths {
  Default = '',
  login = 'login',
  empty = 'empty',
  waiting = 'waiting',
  error = 'error',
  userManagement = 'user-management',
  userList = 'user-list',
  dashboard = 'dashboard',
  users = 'users',
  resetPassword = 'reset-password',
  email = 'email',
  forgotPassword = 'forgot-password',
  dashboardWrapper = ' dashboard-wrapper',
  campaign = 'campaign',
  transcripts = 'transcripts',
  schedulers = 'schedulers',
  media = 'media',
  screen = 'screen',
  updateScreen = 'updateScreen',
  booking = 'booking',
  createBooking = 'create-booking',
}
